name: yaru_example
description: Demonstrate yaru
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.24.3"

dependencies:
  collection: ^1.17.0
  connectivity_plus: ^6.0.4
  flutter:
    sdk: flutter
  flutter_highlight: ^0.7.0
  handy_window: ^0.4.0
  http: ^1.2.2
  path: ^1.9.0
  provider: ^6.1.2
  safe_change_notifier: ^0.3.2
  ubuntu_service: ^0.3.2
  universal_html: ^2.2.4
  url_launcher: ^6.3.0
  yaru:
    path: ../

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  fonts:
    - family: YaruIcons
      fonts:
        - asset: ../assets/yaru_icons.otf
