name: yaru_widgets_example
description: Demonstrate yaru_widgets
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  yaru:
    git: http://github.com/ubuntu/yaru.dart
  yaru_icons: ^0.1.2
  yaru_widgets:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/