name: yaru_widgets_example
description: Demonstrate yaru_widgets
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  collection: ^1.16.0
  connectivity_plus: ^3.0.2
  flutter:
    sdk: flutter
  flutter_highlight: ^0.7.0
  handy_window: ^0.2.0
  http: ^0.13.5
  provider: ^6.0.2
  safe_change_notifier: ^0.2.0
  ubuntu_service: ^0.2.0
  yaru: ^0.4.7
  yaru_icons: ^1.0.0
  yaru_widgets:
    path: ../

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
